name: Merge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: take
        run: bash merge.sh

      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'abpvn-ext.txt'
          default_author: github_actions 
          message: 'Cập nhật bộ lọc: ${{ env.DATE }}'
          push: true
          
